project:
  type: website  # or "document" for a single file

format:
  html:
    embed-resources: true
    css: ec_html_template.css  # Path to your custom CSS
    include-after-body: footer.html  # Include custom footer
    toc: true  # Enable table of contents
    toc-depth: 3  # Specify TOC depth
    number-sections: FALSE  # Enable section numbering
    theme: cosmo  # Optional: Set a built-in theme